version: '3'
services:
  db:
    image: postgres:latest
    container_name: inplace-postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: '${DB_USER_ID}'
      POSTGRES_PASSWORD: '${DB_USER_PASSWORD}'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - ./data:/var/lib/postgresql/data
