version: '3'
services:
  db:
    image: mysql:latest
    container_name: inplace-mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      # MYSQL_HOST_AUTH_METHOD: 'trust'
    volumes:
      # - ./data:/var/lib/mysql/data
      - ./data/mysql/:/var/lib/mysql
